# Generated by Django 5.0.14 on 2025-12-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='output_destination',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
