# Generated by Django 5.0.14 on 2025-12-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_processingjob_output_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='label',
            field=models.CharField(blank=True, default='Action', max_length=100),
        ),
    ]
